package com.codecrafthub.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.Instant;
import java.time.LocalDate;

/**
 * Represents a course tracked by CodeCraftHub.
 */
@JsonIgnoreProperties(ignoreUnknown = false)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Course {

    /**
     * The ID is generated by the service.
     *
     * READ_ONLY prevents clients from supplying or changing the ID.
     */
    @JsonProperty(access = Access.READ_ONLY)
    private Long id;

    /**
     * Course name is required.
     */
    @NotBlank(message = "name is required")
    private String name;

    /**
     * Course description is required.
     */
    @NotBlank(message = "description is required")
    private String description;

    /**
     * Maps the Java field targetDate to the JSON field target_date.
     *
     * The request must use the format YYYY-MM-DD.
     */
    @NotNull(message = "target_date is required")
    @JsonProperty("target_date")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate targetDate;

    /**
     * Status is required and is restricted to the CourseStatus enum values.
     */
    @NotNull(message = "status is required")
    private CourseStatus status;

    /**
     * The timestamp is generated by the application.
     *
     * Clients cannot provide or change it.
     */
    @JsonProperty(value = "created_at", access = Access.READ_ONLY)
    private Instant createdAt;

    /**
     * Required by Jackson when reading JSON.
     */
    public Course() {
    }

    public Course(
            Long id,
            String name,
            String description,
            LocalDate targetDate,
            CourseStatus status,
            Instant createdAt
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.targetDate = targetDate;
        this.status = status;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(LocalDate targetDate) {
        this.targetDate = targetDate;
    }

    public CourseStatus getStatus() {
        return status;
    }

    public void setStatus(CourseStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}